[profile.default]
solc = '0.8.23'
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
bsctest = "${BSCTEST_RPC_URL}"
mantleSepolia = "${MANTLE_SEPOLIA_RPC_URL}"
opbnbtest = "${OPBNBTEST_RPC_URL}"
arbitriumsepolia = "${ARBSEPOLIA_RPC_URL}"

[etherscan]
arbitriumsepolia = { key = "${ARBSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}", chain = "mumbai" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
bsctest = { key = "${BSCTEST_API_KEY}" }
mantleSepolia = { key = "${MANTLE_SEPOLIA_API_KEY}" }
opbnbtest  = { key = "${OPBNBTEST_API_KEY}" }